server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.book_manage.pojo
  configuration:
    map-underscore-to-camel-case: true


